### ISSUE TITLE
MuWire file Details Window positioning issue

### ISSUE THREAD

**Issue by Searinox** [zlatinb/muwire#130]
The Details window that pops up when checking a file that has a comment is positioned with its top left corner in the screen center instead of center X - (window width / 2) , center Y - (window height / 2). No other window I've found does this.

**Comment by zlatinb** [comment]
Hmm, it's fixed in [beta7](https://muwire.com/beta.html) but I don't really know why it was broken in the first place...

**Comment by Searinox** [comment]
Still happening to me, and I did just freshly download beta7 just now. I went to contacts and clicked Browse on one of them and after getting their file list, clicked View Details and the window still appears as described.

**Comment by zlatinb** [comment]
It's not happening on Mac, I'll have to look into windows then.

**Comment by Searinox** [comment]
By the way the Compose Mail window has the same issue(furthermore that window also has a blank title).

**Comment by zlatinb** [comment]
Hi, in the commit referenced above I've properly centered all frames that MuWire opens relative to the main frame.  The next release is going to be in less than two weeks and I will probably not be putting a beta out, so just wait :)

**Comment by zlatinb** [comment]
Quite a few changes came in the last few days, so beta8 is out at the usual place.  Please test :)

**Comment by Searinox** [comment]
Confirmed both windows are spawned at the correct position.
